load("@rules_rust//rust:defs.bzl", "rust_clippy_test", "rust_library", "rust_test", "rustfmt_test")
load("@crates//:defs.bzl", "crate_deps")

DEPS = crate_deps(
    ["anyhow", "serde", "serde_json"],
    package_name = "crates/github_review",
)

rust_library(
    name = "github_review_lib",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "rq_tui_github_review",
    crate_root = "src/lib.rs",
    edition = "2021",
    deps = DEPS,
    visibility = [
        "//crates/storage:__pkg__",
        "//src:__pkg__",
    ],
)

rust_test(
    name = "github_review_tests",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2021",
    deps = DEPS,
    visibility = ["//visibility:private"],
)

rust_clippy_test(
    name = "clippy_test",
    targets = [":github_review_lib", ":github_review_tests"],
    visibility = ["//visibility:private"],
)

rustfmt_test(
    name = "rustfmt_test",
    targets = [":github_review_lib", ":github_review_tests"],
    visibility = ["//visibility:private"],
)

test_suite(
    name = "github_review_test_suite",
    tests = [":github_review_tests", ":clippy_test", ":rustfmt_test"],
    visibility = ["//:__pkg__"],
)
