filegroup(
    name = "migrations",
    srcs = glob(["migrations/*.sql"]),
    visibility = ["//src:__pkg__"],
)

alias(
    name = "rq_tui_lib",
    actual = "//src:rq_tui_lib",
    visibility = ["//visibility:private"],
)

alias(
    name = "rq-tui",
    actual = "//src:rq-tui",
    visibility = ["//visibility:private"],
)

test_suite(
    name = "rq_tui_tests",
    tests = [
        "//src:clippy_test",
        "//src:rq_tui_tests",
        "//src:rustfmt_test",
    ],
    visibility = ["//visibility:private"],
)
