module(
    name = "rq_tui",
    version = "0.1.0",
)

bazel_dep(name = "rules_rust", version = "0.72.0")
bazel_dep(name = "rules_shell", version = "0.6.1")

crate = use_extension("@rules_rust//crate_universe:extensions.bzl", "crate")

crate.from_cargo(
    name = "crates",
    cargo_lockfile = "//:Cargo.lock",
    manifests = [
        "//:Cargo.toml",
        "//crates/domain:Cargo.toml",
    ],
)

use_repo(crate, "crates")
